# NumPy Matrix + Pandas Assignment 


## Q1. Create a 3×3 NumPy Matrix

### Input
```
1 2 3
4 5 6
7 8 9
```

### Output
```python
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```


In [1]:
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Q2. Multiply Matrix by 2

### Input
```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

### Output
```python
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
```


In [2]:
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr*2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## Q3. Find Row-wise Sum

### Output
```python
[ 6 15 24]
```


In [6]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(f"sum of row:{np.sum(arr,axis = 1)}")

sum of row:[ 6 15 24]


## Q4. Find Column-wise Sum

### Output
```python
[12 15 18]
```


In [7]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(f"sum of column:{np.sum(arr,axis = 0)}")

sum of column:[12 15 18]


## Q5. Extract Second Row

### Output
```python
[4 5 6]
```


In [ ]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr[1]) 

[4 5 6]


## Q6. Create DataFrame

| Name | Marks |
|------|------|
| Raj | 80 |
| Amit | 70 |
| Neha | 90 |
| Priya | 85 |


In [27]:
import pandas as pd
b = {
    "Name":["Raj","Amit","Neha","Priya"],
    "Marks":[80,70,90,85]
}
b = pd.DataFrame(b)
print(b)

    Name  Marks
0    Raj     80
1   Amit     70
2   Neha     90
3  Priya     85


## Q7. Add Bonus Column

Bonus = Marks + 5

### Expected Output
```
Raj    80   85
Amit   70   75
Neha   90   95
Priya  85   90
```


In [30]:
import pandas as pd

a = {
    'Name': ['Raj', 'Amit', 'Neha', 'Priya'],
    'Marks': [80, 70, 90, 85]
}
a = pd.DataFrame(a)
a['Bonus'] = a['Marks'] + 5

print(a)


    Name  Marks  Bonus
0    Raj     80     85
1   Amit     70     75
2   Neha     90     95
3  Priya     85     90


## Q8. Display Students Having Marks > 80

### Expected Output
```
Neha   90
Priya  85
```


In [ ]:
import pandas as pd
a = {
    "Name":["Raj", "Suraj", "Neha", "Rishi", "Priya"],
    "Marks":[67,88,90,98,56]
}
a = pd.DataFrame(a)
print(a[a["Marks"] > 80][["Name", "Marks"]])

    Name  Marks
1  Suraj     88
2   Neha     90
3  Rishi     98


## Q9. Print First Row Using iloc

### Expected Output
```
Raj 80
```


In [ ]:

import pandas as pd
d = {
    "Name": ["Raj", "Rishi", "Rahul", "Neha"],
    "Marks": [80, 78, 90, 77]  # FIX: Kept 4 items to match the 4 names
}
d = pd.DataFrame(d)
print(d.iloc[0, 0], d.iloc[0, 1])


Raj 80


## Q10. Print Third Row Using iloc

### Expected Output
```
Neha 90
```


In [ ]:
import pandas as pd

d = {
    "Name": ["Raj", "Rishi", "Rahul", "Neha"],
    "Marks": [80, 78, 90, 77]  
}
d = pd.DataFrame(d)

# This line works perfectly now
print(d.iloc[3, 0], d.iloc[2, 1])


Neha 90


## Q11. Print First 2 Rows Using iloc

### Expected Output
```
Raj 80
Amit 70
```


In [48]:
import pandas as pd

d = {
    "Name": ["Raj", "Amit", "Rahul", "Neha"],
    "Marks": [80, 70, 90, 77]  
}
d = pd.DataFrame(d)

# This line works perfectly now
print(d.iloc[0:2])

   Name  Marks
0   Raj     80
1  Amit     70


## Q12. Print Only Name Column Using iloc

### Expected Output
```
Raj
Amit
Neha
Priya
```


In [51]:
import pandas as pd

d = {
    "Name": ["Raj", "Rishi", "Rahul", "Neha"],
    "Marks": [80, 78, 90, 77]  
}
d = pd.DataFrame(d)

# This line works perfectly now
print(d["Name"])

0      Raj
1    Rishi
2    Rahul
3     Neha
Name: Name, dtype: object


## Q13. Update Amit's Marks to 75

### Expected Output
```
Amit 75
```


In [39]:
import pandas as pd
d = {
    "Name":["Raj", "Amit"],
    "Marks":[56,70]

}
d = pd.DataFrame(d)
d.loc[d["Name"] == "Amit", "Marks"] = 75

print(d)


   Name  Marks
0   Raj     56
1  Amit     75


## Q14. Sort DataFrame by Marks (Descending)

### Expected Output
```
Neha  90
Priya 85
Raj   80
Amit  75
```


In [ ]:
import pandas as pd
a = {
    "Name":["Neha", "Raj", "Amit","Priya"],
    "Marks": [90,80,75,85]
}
a = pd.DataFrame(a)
print(a.sort_values("Marks", ascending=0))
i have this file and iwant you to make a stunning and interactive ui using streamlit but keeps one thing in your mind that is im going to post this ui on linkedin indeed naukri .com so make it  


    Name  Marks
0   Neha     90
3  Priya     85
1    Raj     80
2   Amit     75
